### ISSUE TITLE
Question about usage.

### ISSUE THREAD

**Issue by supesdupes** [woctezuma/steamspypi#11]
Would you be willing to possibly speak over email about the usage of this code? Thanks.

**Comment by woctezuma** [comment]
[README](https://github.com/woctezuma/steamspypi/blob/master/README.md) should be self-explanatory.

If you encounter any issue, it is likely that the Steam API is struggling, which is sadly more and more the case these days.

**Comment by woctezuma** [comment]
If you have any question about SteamSpy API, I would redirect you towards [the original author](https://twitter.com/steam_spy), and the relevant [API docs](https://steamspy.com/api.php), which I have copied [here](https://gist.githubusercontent.com/woctezuma/5aad1b73427d67eb6fb1157c0cf7a8da/raw/fe4b81439ec132216652f78caf74f6069fcaf03c/steam-spy-api-docs.txt).

**Comment by supesdupes** [comment]
I was actually wondering if it would be alright to utilize steamspypi for
academic reasons. I’m a university student and I’d like to use your work to
collect data for an empirical paper I am working on if possible.

**Comment by woctezuma** [comment]
SteamSpyPI is merely a Pythron wrapper around SteamSpy API, so I (the author of the Python wrapper) personally have no issue with you using my wrapper. However, I am not the original author of SteamSpy API (which my wrapper pings), so you could ask the original author (just to be safe):
-   either at https://twitter.com/steam_spy
-   or at https://twitter.com/galyonkin

I would not expect him to refuse. I don't think there is any license tied to the data, and I cannot find any mention of a license on [the About page](https://steamspy.com/about). I think data is public anyway as it is scrapped by SteamSpy from Steam's official API.

Be wary though that SteamSpy API is less convenient to use than before with [the rate-limit and pagination](https://github.com/woctezuma/steamspypi/issues/10) enforced in August.

**Comment by supesdupes** [comment]
Thank you very much for the information. I’ll contact the original author
as well.
