### ISSUE TITLE
Creating loop for request = 'all'

### ISSUE THREAD

**Issue by gric69** [woctezuma/steamspypi#13]
Hi woctezuma,
I hope you are well. I had a list of all games crawled using steamspypi in Dec 2019 and now I need to update my list, but I noticed there that there has been an update and request 'all' does not work without specifying page + the 60 sec wait time!

Since my knowledge of Python is limited and it's worst when it comes to loops. Could you please give me some guidance on how to make a loop for the page numbers to collect data for all the games? 

I simply do not know how to make a loop in there to collect all game data.

**Comment by woctezuma** [comment]
Hi there,

Thank you! I hope you are fine as well..

Sadly, the issue which you mention comes from a change of SteamSpy's API in 2020 (cf. #10):
- rate-limit for requests with `all`:
  - there is a 1-minute cool-down in-between requests.
- pagination for requests with `all`:
  - the first page starts at 0,
  - there are 1000 apps per page.
